import "../../styles/globals.css";
import type { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Gallery",
  description: "Generated by create next app",
  icons: { icon: [{ url: "/favicon.ico", type: "image/x-icon" }] },
};

export default function LoginLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
