// src/app/[locale]/layout.tsx
import type { Metadata } from "next";
import type { ReactNode } from "react";
import { NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { Locale, routing } from "@/i18n/routing";
import { CartProvider } from "@/components/cart/CartContext";

export const metadata: Metadata = {
  title: "Gallery",
  description: "Generated by create next app",
  icons: { icon: [{ url: "/favicon.ico", type: "image/x-icon" }] },
};

// Gera rotas por locale
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

// Desliga cache nesta subtree (facilita debug)
export const revalidate = 0;

export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ locale: Locale }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);

  let messages: Record<string, unknown>;
  try {
    messages = (await import(`@/locales/${locale}/common.json`)).default;
  } catch {
    messages = (await import("@/locales/pt/common.json")).default;
  }

  return (
    <NextIntlClientProvider locale={locale} messages={messages as any}>
      <CartProvider>{children}</CartProvider>
    </NextIntlClientProvider>
  );
}
