// src/app/[locale]/layout.tsx
import '../../styles/globals.css';
import type {Metadata} from 'next';
import type {ReactNode} from 'react';
import {Geist, Geist_Mono} from 'next/font/google';
import {NextIntlClientProvider} from 'next-intl';
import {setRequestLocale} from 'next-intl/server';
import {Locale, routing} from '@/i18n/routing';

// 🔥 ADICIONAR O TEU PROVIDER CLIENTE PARA NEXTAUTH
import AuthProvider from '@/components/AuthProvider';

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Gallery',
  description: 'Generated by create next app',
  icons: { icon: [{ url: '/favicon.ico', type: 'image/x-icon' }] }
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export const revalidate = 0;

export default async function RootLayout({
  children,
  params
}: {
  children: ReactNode;
  params: Promise<{ locale: Locale }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);

  let messages: Record<string, unknown>;
  try {
    messages = (await import(`@/locales/${locale}/common.json`)).default;
  } catch {
    messages = (await import('@/locales/pt/common.json')).default;
  }

  return (
    <html lang={locale} className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {/* 🔥 NextAuth wrapper */}
        <AuthProvider>
          {/* i18n wrapper */}
          <NextIntlClientProvider locale={locale} messages={messages as any}>
            {children}
          </NextIntlClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
